basePath: /v1
definitions:
  hall.Resource:
    properties:
      ID:
        type: integer
      VIP:
        type: boolean
      seats:
        type: integer
    type: object
  movie.Resource:
    properties:
      Duration:
        type: string
      ID:
        type: integer
      Name:
        type: string
    type: object
  session.Resource:
    properties:
      ID:
        type: integer
      Movie name:
        type: string
      Starts_at:
        type: string
      VIP:
        type: boolean
      hall_id:
        type: integer
      movie_id:
        type: integer
    type: object
  tckgenerator.Link:
    properties:
      url:
        type: string
    type: object
  tickets.Resource:
    properties:
      Starts_at:
        type: string
      id:
        type: integer
      price:
        type: number
      seat:
        type: integer
      session_ID:
        type: integer
      title:
        type: string
      user_ID:
        type: integer
    type: object
  user.Resource:
    properties:
      ID:
        type: integer
      email:
        type: string
      password:
        type: string
    type: object
  user_privileges.Resource:
    properties:
      Email:
        type: string
      ID:
        type: integer
      Privilege:
        type: string
      Privilege_id:
        type: integer
      User_id:
        type: integer
    type: object
host: localhost:8085
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample cinetickets server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cinetickets API
  version: "1.0"
paths:
  /halls:
    get:
      consumes:
      - application/json
      description: get halls
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/hall.Resource'
              type: array
            type: array
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: List halls
      tags:
      - Halls
    post:
      consumes:
      - application/json
      description: Creates hall and returns created object
      parameters:
      - description: The body to create a hall
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/hall.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hall.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Create hall
      tags:
      - Halls
  /halls/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes hall
      parameters:
      - description: Hall ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Delete hall
      tags:
      - Halls
    get:
      consumes:
      - application/json
      description: Gets hall
      parameters:
      - description: Hall ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hall.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Get hall
      tags:
      - Halls
  /halls/{id}/sessions:
    post:
      consumes:
      - application/json
      description: Creates session and returns created object
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: integer
      - description: The body to create a session
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/session.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/session.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Create session
      tags:
      - Sessions
  /movies:
    get:
      consumes:
      - application/json
      description: get movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/movie.Resource'
              type: array
            type: array
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: List movie
      tags:
      - Movies
    post:
      consumes:
      - application/json
      description: Creates movie and returns created object
      parameters:
      - description: The body to create a movie
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/movie.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/movie.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Create movie
      tags:
      - Movies
  /movies/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes movie
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Delete movie
      tags:
      - Movies
    get:
      consumes:
      - application/json
      description: Gets movie
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/movie.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Get movie
      tags:
      - Movies
  /sessions:
    get:
      consumes:
      - application/json
      description: get sessions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/session.Resource'
              type: array
            type: array
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: List session
      tags:
      - Sessions
  /sessions/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes session
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Delete session
      tags:
      - Sessions
    get:
      consumes:
      - application/json
      description: Gets session
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/session.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Get session
      tags:
      - Sessions
  /sessions/{id}/tickets:
    post:
      consumes:
      - application/json
      description: Creates ticket and returns created object
      parameters:
      - description: ticket ID
        in: path
        name: id
        required: true
        type: integer
      - description: The body to create a ticket
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/tickets.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tickets.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Create ticket
      tags:
      - Tickets
  /signin:
    post:
      consumes:
      - application/json
      description: Signin
      parameters:
      - description: Email and password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/user.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: "Bad Request"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      summary: Signin
      tags:
      - Users
  /signup:
    post:
      consumes:
      - application/json
      description: Signup
      parameters:
      - description: Email and password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/user.Resource'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: "Bad Request"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      summary: Signup
      tags:
      - Users
  /tickets:
    get:
      consumes:
      - application/json
      description: get tickets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/tickets.Resource'
              type: array
            type: array
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: List ticket
      tags:
      - Tickets
  /tickets/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes ticket
      parameters:
      - description: ticket ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Delete ticket
      tags:
      - Tickets
    get:
      consumes:
      - application/json
      description: Gets ticket
      parameters:
      - description: ticket ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tickets.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Get ticket
      tags:
      - Tickets
  /tickets/{id}/download:
    get:
      consumes:
      - application/json
      parameters:
      - description: ticket ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tckgenerator.Link'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Download ticket
      tags:
      - Tickets
  /user_privileges:
    get:
      consumes:
      - application/json
      description: get User Privileges
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/user_privileges.Resource'
              type: array
            type: array
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: List User Privileges
      tags:
      - User Privileges
    post:
      consumes:
      - application/json
      description: Creates User Privilege and returns created object
      parameters:
      - description: The body to create a User Privilege
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/user_privileges.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_privileges.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Create User Privilege
      tags:
      - User Privileges
  /user_privileges/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes User Privilege
      parameters:
      - description: User Privilege ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Delete User Privilege
      tags:
      - User Privileges
    get:
      consumes:
      - application/json
      description: Gets User Privilege
      parameters:
      - description: User Privilege ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_privileges.Resource'
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "422":
          description: "Unprocessable Entity"
        "500":
          description: "Internal Server Error"
      security:
      - ApiKeyAuth: []
      summary: Get User Privilege
      tags:
      - User Privileges
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
